### ISSUE TITLE
how to scrap the web content by python.

### ISSUE THREAD

**Issue by EnchanterDeveloper** [EnchanterDeveloper/gitTutorial#1]

**Comment by EnchanterDeveloper** [comment]
@oneway-fullstack, you can add your feedback.

**Comment by oneway-fullstack** [comment]
@EnchanterDeveloper plz share your skype id, let's talk in detail.

**Comment by EnchanterDeveloper** [comment]
hi @oneway-fullstack , i am so glad to contact you in spite of being directly.
you can send your feedback as comment. i will download later.
and if i need to contact you later, i will ask sj or use this channel.
i can not contact you via skype or any talking tool because of some restriction.
to research some subject, i am online now. it is just only to search something on google.com.
please send the instruction for my new startup.
which skill and technique are necessary, how to educate them, what are any extra skill, and etc.

**Comment by oneway-fullstack** [comment]
I understand your situation.
It's been changed so much on this industry these years.
I recommend some stacks.
1. Javascript & NodeJs / React
2. AWS & Terraform / DevOps
3. Python & Django / Vue
4. Solidity & Web3 / Blockchain
5. ChatGPT

Regarding to the way how to get a job. with my experience, I recommend you to find a native partner in social like linkedin.
Its the best case if he's a developer, and then you need to persuade him to share some info and discuss in details.
So basically you all guys must be good at English. This is the key break.
Another case, it's not good to describe here directly.

Regarding to the education, you need to search for interview skills such as live coding, system design.
In advance, you are supposed to build a good resume which all HR manager review and prepare the experience wonderfully.

Once again, English is the most important rather than programming skills.
Even though you don't know how to program, AI is so advanced in this age, ChatGPT always gives us the correct answer about everything coding, mentoring, training or something.
Let me know your thoughts.

Hopefully this can help you out.
Thanks
